### ISSUE TITLE
Tension with QPA declarations

### ISSUE THREAD

**Issue by HereAround** [homalg-project/ComplexesForCAP#4]
```
LoadPackage(  "ComplexesC" );
LoadPackage( "QPA" );
```

It seems, that these packages define similar methods. Therefore, I obtain the warning (which currently triggers my tests to fail): 

```
#I  method installed for IdentityMatrix matches more than one declaration
#I  method installed for RowsOfMatrix matches more than one declaration
#I  method installed for RowsOfMatrix matches more than one declaration
#I  method installed for RowsOfMatrix matches more than one declaration
#I  method installed for UnderlyingField matches more than one declaration
#I  method installed for + matches more than one declaration
#I  method installed for IsZero matches more than one declaration
#I  method installed for InverseMutable matches more than one declaration
#I  method installed for IsZero matches more than one declaration
#I  method installed for + matches more than one declaration
#I  method installed for InverseMutable matches more than one declaration
#I  method installed for IsZero matches more than one declaration
#I  method installed for + matches more than one declaration
#I  method installed for InverseMutable matches more than one declaration
```

Any chance to resolve this? I also raised this issue at https://github.com/oysteins/QPA2/issues/37. Note however, that this only occurs with the QPA2-version available at https://github.com/homalg-project/QPA2.

**Comment by kamalsaleh** [comment]
If you remove `ComplexesCategories` from the dependencies, the same warnings will still be there. I have fixed the warnings in this branch https://github.com/kamalsaleh/QPA2/tree/fix_warnings . I will prepare a PR in these fixes to `homalg-project/QPA` until Oystein is again active in developing the `QPA` package.

**Comment by HereAround** [comment]
Thank you Kamal!

**Comment by mohamed-barakat** [comment]
Thanks, Martin for reporting and Kamal for the quick fix.
